# 格问题
## 定义4
格$\mathcal{L} \subset \mathbb{R}^n$的最短距离是指格中最短的非零向量：$ \lambda_1(\mathcal{L})=\min_{v \in L,v\neq \{0\}} ||v||$

## 两种签名算法基于CVP和SIS

**例：** 随机生成矩阵$A \in \mathbb{Z}_q^{n \times m}$

In [1]:
import numpy as np

# 定义参数，n、m为矩阵维度，q是模数，d是矩阵元素范围
n, m, q, d = 4, 5, 7, 10
# 求mq
mq = int((q-1)/2)
mq

3

In [2]:
# 随机生成元素为[-d, d]之间的整数矩阵
A = np.random.randint(-d, d+1, (n, m))
A

array([[ -5,  -3,   4,   6,  -6],
       [  4,  -4,  -1,  10,   6],
       [  3,   0,  10,  -4,  -5],
       [ -2,   4,   0, -10,   3]])

In [3]:
# 矩阵中mod p大于mq的元素 q - q
A = np.where(A % q <= mq, A, A % q - q)
A

array([[-5, -3, -3, -1, -6],
       [-3, -4, -1, 10, -1],
       [ 3,  0, 10, -4, -5],
       [-2, -3,  0, -3,  3]])

In [4]:
# 矩阵中mod q小于等于mq的元素 mod q
A = np.where(A % q > mq, A, A % q)
A

array([[ 2, -3, -3, -1,  1],
       [-3,  3, -1,  3, -1],
       [ 3,  0,  3,  3,  2],
       [-2, -3,  0, -3,  3]])

In [5]:
# 也可以调用Simchain中的函数求解
from simchain.lbc import convert_to_Zq
B = np.random.randint(-d, d+1, (n, m))
convert_to_Zq(B, q)

array([[ 1,  2,  2,  1,  2],
       [ 2, -2,  1,  2,  3],
       [-3, -3, -3, -3,  2],
       [-2, -1,  2, -3,  2]])

# 最近向量问题
Babai最近向量算法：已知$n$维格$\mathcal{L} \subset \mathbb{R}^n$，$B=\{ b_i \in \mathbb{R}^n: 1 \leqslant i \leqslant n \}$是$\mathcal{L}$的一组基，$w \in \mathcal{R}^n$是非格向量。如果$B$中向量两两正交或接近两两正交，则可以采用Babai算法求解CVP。

**例：** 用“好”基$\{ (1,0),(0.2,0.9)\}$计算向量$(2.3,3.06)$的最近向量。

In [6]:
import simchain.lbc as lbc
import numpy as np
# 创建基
basis = np.array([[1, 0], [0.2, 0.9]])
# 列向量构造基
basis = basis.T
# 创建格
l = lbc.Lattice(basis)
# 计算格的Hadamard比，是“好”基
lbc.hadamard(basis)

0.988021791350754

In [7]:
# 创建非格点w
w = [2.3, 3.06]
l.contains(w)

False

In [8]:
# 用格的基表示w，得到系数x
x = np.linalg.solve(basis, w)
x

array([1.62, 3.4 ])

In [9]:
# 将x四舍五入
x = np.around(x).astype('int')
x

array([2, 3])

In [10]:
# 计算最近向量v
v = np.dot(l.basis, x)
v

array([2.6, 2.7])

**例：** 用“坏”基$\{ (17.8, 12.6),(28.4, 19.8)\}$计算向量$(2.3, 3.06)$的最近向量。

In [11]:
basis = np.array([[17.8, 12.6], (28.4, 19.8)])
basis = basis.T
l = lbc.Lattice(basis)
lbc.hadamard(basis)

0.08457029589089926

In [12]:
l.contains(w)

False

In [13]:
x = np.linalg.solve(basis, w)
x = np.around(x).astype('int')
v = np.dot(l.basis, x)
x

array([ 8, -5])

In [14]:
v

array([0.4, 1.8])