# 格基础知识

## 定义1 
已知$B=\{b_i \in \mathbb{R}^n:i \leqslant i \leqslant n \}$是$n$个线性无关的向量，则基于$B$的$n$维格$\mathcal{L}$表示为
$$\mathcal{L}(B)=\{\Sigma^n_{i=1}a_ib_i:a_i\in \mathbb{Z}\}$$
其中，$\mathbb{R}^n$表示$n$维实数域（$n$维向量中的每个元素都是实数），$b_i$的长度为$n$，$\mathbb{Z}$表示整数域。  
格具有如下两个性质：  
- 加法子群，$0 \in \mathcal{L} \subset \mathbb{R}^n$且对于任意$x,y \in \mathcal{L} \subset \mathbb{R}$，有$-x,x+y \in \mathcal{L} \subset \mathbb{R}$；
- 离散性，对于任意$x \in \mathcal{L}$，存在$\epsilon > 0$，满足$\mathcal{L} \cap \{y \in \mathbb{R}^n:||x-y|| < \epsilon \}=\{x\}$

**例：** 考虑一个三维的格$\mathcal{L} \subset \mathbb{R}^3$，以下三个向量构成其一组基：$$\begin{array}{ccc}
b_1 = (2,1,3)^T \\
b_2 = (1,2,0)^T \\
b_3 = (2,-3,-5)^T
\end{array}$$
试判断向量$v_1=(4,2,6)和v_2=(-20,24,10)$是否在格$\mathcal{L}$中。  
要判断向量$b$是否在格中，只需要通过求解$Ba=b$，如果$a$的所有元素都为整数，则表示$b$在格中。

In [1]:
import numpy as np

# 创建矩阵
basis = np.array([[2,1,3], [1,2,0], [2,-3,-5]])
# 转置，列向量构造基
basis = basis.T
basis

array([[ 2,  1,  2],
       [ 1,  2, -3],
       [ 3,  0, -5]])

In [2]:
# 创建向量v1
v1 = [4, 2, 6]
# 求解Ba1 = v1
a1 = np.linalg.solve(basis, v1)
# 元素均为整数，v1在格中
a1

array([2., 0., 0.])

In [3]:
# 创建向量v2
v2 = [-20, 24, 10]
# 求解Ba2 = v2
a2 = np.linalg.solve(basis, v2)
# 元素不为整数，v2不在格中
a2

array([-6.94444444,  6.22222222, -6.16666667])

In [4]:
import simchain.lbc as lbc

# 通过基创建格
l = lbc.Lattice(basis)
# 调用contains方法判断
l.contains(v1)

True

In [5]:
l.contains(v2)

False

In [6]:
# 随机创建一个非格中的向量
l.non_lattice_point()

array([ -0.83,  -6.51, -13.48])

In [7]:
# 随机创建一个格中的向量
l.lattice_point()

array([ 12, -19,  -5])

## 命题1
如果$B$和$C$是$n$维格$\mathcal{L}$的两组基，则存在幺模矩阵$A$，满足$C=AB$，幺模矩阵满足$A \in \mathbb{Z}^n$，且$det A = \pm 1$。

## 定义2
已知$B=\{b_1 \in \mathbb{R}^n:i \leqslant i \leqslant n\}$是$n$维格$\mathcal{L}$的一组基。则格$\mathcal{L}$关于$B$的元域$\mathcal{F}$表示为$\mathcal{F}(B)=\{\Sigma^n_{i=1}a_ib_i:a_i \in [0,1)\}$

**例：** 随机创建一个幺模矩阵。  
幺模矩阵的特点是所有元素都为整数，且行列式为$\pm1$，采用如下方法随机创建。随机幺模矩阵$A=T_1T_2,T_i=L_iU_i$，其中$L_i$和$U_i$分别为下、上三角矩阵，且对角线元素为$\pm1$。

In [8]:
import numpy as np
# 随机创建一个元素在[-10, 10)范围内4阶方阵
A = np.random.randint(-10, 10, (4,4))
A

array([[  1,   4,   3,  -7],
       [-10,  -5,   8,   5],
       [ -7,   0,  -2,   5],
       [  0,   8,  -6,   8]])

In [9]:
B = np.random.randint(-10, 10, (4,4))
# 获取方阵的上三角，不包括对角线
triu1 = np.triu(A, 1)
triu2 = np.triu(B, 1)
triu1

array([[ 0,  4,  3, -7],
       [ 0,  0,  8,  5],
       [ 0,  0,  0,  5],
       [ 0,  0,  0,  0]])

In [10]:
# 获取方阵的下三角，不包括对角线
tril1 = np.tril(A, -1)
tril2 = np.tril(B, -1)
tril1

array([[  0,   0,   0,   0],
       [-10,   0,   0,   0],
       [ -7,   0,   0,   0],
       [  0,   8,  -6,   0]])

In [11]:
# 随机创建两个元素为-1,0,1的向量
I1 = np.random.randint(-1, 2, 4)
I2 = np.random.randint(-1, 2, 4)
print(I1)
print(I2)

[ 1 -1 -1 -1]
[ 0  1 -1  0]


In [12]:
# 将向量中为0的元素用1代替
I1 = np.where(I1 != 0, I1, 1)
# 将向量中为0的元素用-1代替
I2 = np.where(I2 != 0, I2, -1)
I1, I2

(array([ 1, -1, -1, -1]), array([-1,  1, -1, -1]))

## 命题2
已知$B=\{b_i \in \mathbb{R}^n:1 \leqslant i \leqslant n\}$是$n$维格$\mathcal{L}$的一组基，$\mathcal{F}$是$n$维格$\mathcal{L}$的一个元域，则对于任意向量$w \in \mathbb{R}^n$，存在唯一的向量$u \in \mathcal{F}$和$v \in \mathcal{L}$，满足$w=u+v$。

**例：** 随机生成一个元域向量。

In [13]:
# 随机创建一个元素为[0, 1)的向量
v = np.random.uniform(0, 1, 3)
v

array([0.30491912, 0.39455374, 0.34302729])

In [14]:
# 创建元域中的向量
b = np.dot(l.basis, v)
b

array([ 1.69044657,  0.06494473, -0.80037909])

In [15]:
# 通过格对象创建
l.fundamental_point()

array([ 3.21248577, -1.61319496, -3.60245827])

## 定义3
已知$\mathcal{F}$是$n$维格$\mathcal{L}$的一个元域，则$\mathcal{L}$的行列式det $\mathcal{L}$为元域$\mathcal{F}$的$n$维体积。
## 命题3
已知$B=\{b_i \in \mathbb{R}^n:1 \leqslant i \leqslant n\}$是$n$维格$\mathcal{L}$的一组基，则有det $\mathcal{L}$=$|$det $B|$。
## 命题4
已知$B=\{b_i \in \mathbb{R}^n:1 \leqslant i \leqslant n\}$，则有Hadamard不等式$$det \mathcal{L} \leqslant \Pi_{i=1}^n||b_i||$$

**例：** 考虑一个四维的格$\mathcal{L} \subset \mathbb{R}^4$，其一组基由四个向量构成$$\begin{array}{ccc} 
b_1 = (-8, 4, 0, 1)^T \\
b_2 = (-5, 1, -6, 1)^T \\
b_3 = (-3, -1, 8, 8)^T \\
b_4 = (-3, -7, -3, 2)^T 
\end{array}$$计算该组基的Hadmard比，并随机生成一对“好”基和“坏”基。

In [16]:
import numpy as np
basis = np.array([[-8, 4, 0 ,1], [-5, 1, -6, 1], [-3, -1, 8, 8], [-3, -7, -3, 2]])
basis = basis.T
basis

array([[-8, -5, -3, -3],
       [ 4,  1, -1, -7],
       [ 0, -6,  8, -3],
       [ 1,  1,  8,  2]])

In [17]:
# 计算基的行列式
det = abs(np.linalg.det(basis))
# 计算基的二范数乘积
mult = np.prod(np.linalg.norm(basis, axis=0))
# 计算Hadamard比
ratio = (det/mult)**(1./4)
ratio

0.7869588900998594

### 生成“好”基
#### 方法一

In [18]:
import simchain.lbc as lbc
# 定义维度和Hadamard比阈值
n, ur = 4, 0.9
# 定义基向量元素的取值
lb, ub = -10, 10
# 初始化“好”基
good = np.random.randint(lb, ub, (n, n))
# 满足“好”集条件退出循环
while lbc.hadamard(good) < ur:
    good = np.random.randint(lb, ub, (n, n))
good

array([[ 2,  3,  3, -9],
       [-4, -8,  7, -6],
       [ 8, -7, -9, -3],
       [ 6,  6,  7,  4]])

In [19]:
# “好”基的Hadamard比
lbc.hadamard(good)

0.9223123719070113

#### 方法二

In [20]:
good = np.random.randint(lb, ub, (n, n))
# 生成单元矩阵
I = np.identity(n, dtype='int')
k = 100
good = good + k * I
lbc.hadamard(good)

0.9929048059721531

### 生成“坏”基
#### 方法一

In [21]:
# 随机生成幺模矩阵
u = lbc.rand_unimodular_matrix(n)
# 初始化“坏”基
bad = np.dot(u, good)
# 满足“坏”基条件退出循环
while lbc.hadamard(bad) > 0.1:
    u = lbc.rand_unimodular_matrix(n)
    bad = np.dot(u, good)
bad

array([[  97,  681, -145,  281],
       [ 566, 4169, -674, 1592],
       [  69, 2024, 1342, -786],
       [  -2,   -1,    7,  100]])

In [22]:
# “坏”基的Hadamard比
lbc.hadamard(bad)

0.060234400129852365

#### 方法二

In [23]:
# 初始化“坏”基
bad = good.T.copy()
# 满足“坏”基条件退出循环
while lbc.hadamard(bad.T) > 0.1:
    # 随机生成整数
    r = np.random.randint(1, 10, (n , 1))
    # 随机选择需要修改的向量
    bad += np.random.permutation(bad)
# 转置
bad = bad.T
bad

array([[188, -11,   6, -11],
       [  0,  96, -18,  96],
       [-18,  -4, 212,  -4],
       [ -4,  99,  14,  99]])

In [24]:
lbc.hadamard(bad)

0.0